Multikey filter
SoftServeSalesforce/ss_admin_console pull request #37
Opened 2022-06-25 10:46 UTC by Taraass

2022-06-29 13:00 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +    private Map<String, Set<Object>> getConstantFields() {
Does the method return fields or values? Why constants, I'd rename it to getKeyFieldValues

2022-06-29 13:07 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +        for (SObjectField field: allFields) {
Should you use allFields, or keyFields?

2022-06-29 13:28 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
>      private Map<String, Set<Object>> constantFields;
Do you need this field? It's used only to build a SOQL. So you can store the values as s method local variable

2022-06-29 13:30 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +    private List<SObject> constantSObjects;
Where is it used?

2022-06-29 13:32 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +            for (SObjectField keyField: keyFields) {
```suggestion
            for (SObjectField keyField : keyFields) {
```

2022-06-29 13:35 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +            String concatenatedString = '';
```suggestion
            String recordKeysFingerprint = '';
```

2022-06-29 13:37 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +                    .setStatus(SSACConstants.DUPLICATED_STATUS)
Format code here

2022-06-29 13:37 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +                .setStatus(SSACConstants.OK_STATUS)
and here

2022-06-29 13:40 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +    private Map<String, SObject> generateExistentMap(){
```suggestion
    private Map<String, SObject> generateExistentMap() {
```

2022-06-29 13:42 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACLogger.cls
> +                    Message__c = duplicateResults.size() < 50 ? this.util.keysToString(duplicateResults) : this.handleAmountOfRecordsProceed(duplicateResults.size()),
Extract '50' to constant

2022-06-30 08:51 UTC, Taraass commented on ss_admin_console/main/default/classes/SSACFilter.cls
> +        this.existentMap = this.generateExistentMap();
It is used in getFilteredRecords(), when we are filtering by the status

2022-07-03 10:54 UTC, mykhaylo-partyka requested changes

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +            if (existentMap.get(recordKeysFingerprint) != null) {
Extract `existentMap.get(recordKeysFingerprint)` to local variable and reuse it later (e.g. on line 32)

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +                            matchedNonKeyFields += 1;
```suggestion
                            matchedNonKeyFields++;
```

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +        result += ' FROM '+ String.valueOf(sObjectApiName) + ' WHERE ';
Don't use valueOf(), use getDEscribe().getName().
Salesforce documentation doesn't say clearly that String.valueOf(SObject) will return SObject name.

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +                result += (value instanceof String) ? '\'' + value + '\',' :  value + ',';
Escape quotes in string values with String.escapeSingleQuotes() method to prevent SOQL injections.

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +        result = result.removeEnd(result.right(4));
```suggestion
        result = result.removeEnd(result.right(5));
```

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +    // // existent sobject extraction
```suggestion
    // existent sobject extraction
```

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +    @TestVisible
@TestVisible should be applied to private methods only

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +    private Map<String, SObject> generateExistentMap(List<SObject> existentRecords) {
```suggestion
    private Map<String, SObject> generateExistentRecordsMap(List<SObject> existentRecords) {
```

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +              for (SObject existSObj : existentRecords) {
Format code accordingly

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +            constantValues.put(String.valueOf(field), values);
use field.toString() instead

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACLogger.cls
> +        return String.valueOf(size) + ' records ' + ((size > 1) ? 'are' : 'is') + ' tested!';
Why present instead of past?

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACLogger.cls
> +        return String.valueOf(size) + ' records ' + ((size > 1) ? 'were' : 'was') + ' proceed!';
Why exclamation mark?

2022-07-03 10:54 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/SSACLogger.cls
>          return 'Successfully upserted ' + sObjectApiName + '`s records. ';
```suggestion
        return 'Successfully upserted ' + sObjectApiName + '\'s records. ';
```

2022-07-05 15:21 UTC, Taraass commented on ss_admin_console/main/default/classes/SSACDataFilter.cls
> +            recordKeysFingerprint = recordKeysFingerprint.removeEnd(recordKeysFingerprint.right(1));
we need this to delete "_" at the end of concatenated string

2022-07-06 13:22 UTC, mykhaylo-partyka requested changes

2022-07-06 13:22 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/FieldReference.cls
> +
Remove blank like here

2022-07-11 07:48 UTC, mykhaylo-partyka requested changes

2022-07-11 10:32 UTC, mykhaylo-partyka requested changes

2022-07-13 10:02 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/actions/SSACSObjectAction.cls
> +                recordKeysFingerprint += String.valueOf(keyField.getFrom(item)).toLowerCase() + '_';
bad formating

2022-07-13 10:03 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/actions/SSACSObjectAction.cls
> +			String recordKeysFingerprint = '';
Replace tabs with spaces

2022-07-13 10:03 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/actions/SSACSObjectAction.cls
> +			recordKeysFingerprint = recordKeysFingerprint.removeEnd('_');
replace tabs with spaces

2022-07-13 10:04 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/actions/SSACProductDataAction.cls
> +        for(String obj: entriesMap.keySet()) {
```suggestion
        for (String obj: entriesMap.keySet()) {
```

2022-07-13 10:04 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/actions/SSACProductDataAction.cls
> +                    productByProductCode)
bad indentation

2022-07-14 10:36 UTC, jsNickOs approved these changes

2022-07-14 10:36 UTC, jsNickOs commented on ss_admin_console/main/default/classes/actions/SSACDataHandler.cls
> +            Map<String, String> referenceFieldToKeyFields, Map<String, String> referenceFieldToSObjectName) {
Why did you add blank before line of code?

2022-07-14 12:03 UTC, mykhaylo-partyka approved these changes

2022-07-14 13:22 UTC, merged