fix format
SoftServeSalesforce/ss_admin_console pull request #44
Opened 2022-07-20 14:25 UTC by matrunych

2022-07-20 17:10 UTC, Taraass requested changes

2022-07-20 17:10 UTC, Taraass commented on ss_admin_console/main/tests/classes/SetUtilsTest.cls
> +        Object result = SetUtils.toSetOfType(field,objs);
the same here

2022-07-20 17:10 UTC, Taraass commented on ss_admin_console/main/tests/classes/SetUtilsTest.cls
> +        Object result = SetUtils.toSetOfType(field,objs);
and here

2022-07-20 17:10 UTC, Taraass commented on ss_admin_console/main/tests/classes/SetUtilsTest.cls
> +        Object result = SetUtils.toSetOfType(field,objs);
and here

2022-07-20 17:10 UTC, Taraass commented on ss_admin_console/main/tests/classes/SetUtilsTest.cls
> +        Object result = SetUtils.toSetOfType(field,objs);
and heree

2022-07-22 10:24 UTC, mykhaylo-partyka approved these changes

2022-07-22 10:38 UTC, merged