fixing comments
SoftServeSalesforce/ss_admin_console pull request #45
Opened 2022-07-20 14:28 UTC by Taraass

2022-07-20 14:34 UTC, matrunych commented on ss_admin_console/main/tests/classes/SSACDataFilterTest.cls
>  @isTest
isTest -> IsTest

2022-07-21 10:45 UTC, mykhaylo-partyka requested changes

2022-07-21 10:45 UTC, mykhaylo-partyka commented on ss_admin_console/main/tests/classes/SSACDataFilterTest.cls
>          } catch (Exception e) {
```suggestion
        } catch (QueryException e) {
```

2022-07-21 10:45 UTC, mykhaylo-partyka commented on ss_admin_console/main/tests/classes/SSACDataFilterTest.cls
> +            System.assert(e instanceof QueryException, 'Exception Type is not QueryException');
```suggestion
            // The exception is expected here
```

2022-07-22 10:23 UTC, mykhaylo-partyka approved these changes

2022-07-22 10:35 UTC, merged