Datafeeder redesign
SoftServeSalesforce/ss_admin_console pull request #67
Opened 2022-08-29 13:23 UTC by Taraass

2022-08-30 15:15 UTC, mykhaylo-partyka requested changes

2022-08-30 15:15 UTC, mykhaylo-partyka commented on ss_admin_console/main/default/classes/poc/feeder/UnitOfWorkHelper.cls
> +        return recordKeysFingerprint.removeEnd('_');
is it required?

2022-08-30 16:13 UTC, Taraass commented on ss_admin_console/main/default/classes/poc/feeder/BaseDataFeeder.cls
> +                logger.error('FAILED: No records to be inserted. Check the sample data again.');
but they are not exist in list of sample data, because filter did not return it. So it means we have nothing to insert

2022-08-30 16:20 UTC, Taraass commented on ss_admin_console/main/default/classes/poc/feeder/UnitOfWorkHelper.cls
> +        fflib_SObjectUnitOfWork uow =
i am about to use it for registerNew after coming up with idea of getting a parentId implementation and then use it for commitWork

2022-09-03 21:49 UTC, Taraass commented on ss_admin_console/main/default/classes/poc/feeder/UnitOfWorkHelper.cls
> +public with sharing class UnitOfWorkHelper {
will be in next commit

2022-09-21 09:55 UTC, closed without merging